package com.has.base;

import java.io.Serializable;

/**
 * Usage is to sore all possible command names
 * 
 * @author Ufuk BOMBAR
 * @since 28.04.2018 10:48
 * @version 1.0
 */
public enum CommandName
{
    // BASIC NON-DEVICE COMMAND NAMES
    GET_CONFIG,
    GET_OPTIONS, 
    SET_NOBODY_HOME_MODE,
    ENABLE_DEVELOPER_SESSION,
    NOTIFICATION,
    RESPONSE,

    // DEVICE COMMANDS
    GET_TEMPERATURE,
    GET_DISTANCE,
    GET_INTRUSION_TIMESTAMP,
    GET_BUTTON_STATE,
    GET_LIGHT_INTENSITY,
    SET_LIGHT_STATE,
    GET_LIGHT_STATE,
    SET_FAN_STATE,
    GET_FAN_STATE,
    GET_HEATER_STATE,
    SET_HEATER_STATE,
    GET_CAMERA_STATE,
    SET_CAMERA_STATE,
    GET_CAMERA_IMAGE,
    RECORD_FOR,
    GET_LPG_CONCENTRATION,
    GET_METHANE_CONCENTRATION,
    GET_ETHANE_CONCENTRATION,
    GET_PROPANE_CONCENTRATION,
    GET_CO_CONCENTRATION,
    GET_SMOKE_CONCENTRATION,
    GET_GAS_CONCENTRATION,

    // NON-DEVELOPER DATABASE COMMANDS
    GET_TEMP_DATA,
    GET_GAS_DATA,
    GET_CONSUMPTION_DATA,
    UPDATE_CONSUMPTION_DATABASE,
    

    // DEVELOPER DEVICE COMMANDS
    SET_TEMPERATURE,
    SET_DISTANCE,
    SET_INTRUSION_TIMESTAMP,
    SET_BUTTON_STATE,
    SET_LIGHT_INTENSITY,
    SET_CAMERA_IMAGE,
    SET_LPG_CONCENTRATION,
    SET_METHANE_CONCENTRATION,
    SET_ETHANE_CONCENTRATION,
    SET_PROPANE_CONCENTRATION,
    SET_CO_CONCENTRATION,
    SET_SMOKE_CONCENTRATION,
    SET_GAS_CONCENTRATION,

    // DEVELOPER DATABASE COMMANDS
    RESET_DATABASE,
    RUN_DATABASE_QUERY,
    SET_TEMP_DATA,
    SET_GAS_DATA,
    SET_CONSUMPTION_DATA;
}